//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acn.BA.Gamification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedDonation
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string User1Name { get; set; }
        public string User1Email { get; set; }
        public string User2Name { get; set; }
        public string User2Email { get; set; }
        public string User3Name { get; set; }
        public string User3Email { get; set; }
        public string LoadError { get; set; }
    }
}
