//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Link.BA.Donate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.Donation = new HashSet<Donation>();
        }
    
        public int DonorId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string NIF { get; set; }
        public byte[] Picture { get; set; }
        public bool Organization { get; set; }
        public int DonorAddressId { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string PictureContentType { get; set; }
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        public virtual DonorAddress DonorAddress { get; set; }
    }
}
