
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Link.BA.Donate.Models
{

using System;
    
public partial class QuantitiesByProductEntity
{

    public string Name { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public string UnitOfMeasure { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
