<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<NoWarn>$(NoWarn);SA1101;SA1204;SA1311;SA1611;SA1615;SA1623;SA1642</NoWarn>
		<Nullable>annotations</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.Monitor.Query" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Azure.Storage.Queues" />
		<PackageReference Include="Microsoft.ApplicationInsights" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="RestSharp" />
		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Common\BancoAlimentar.AlimentaEstaIdeia.Common.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Model\BancoAlimentar.AlimentaEstaIdeia.Model.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.Model\BancoAlimentar.AlimentaEstaIdeia.Sas.Model.csproj" />
		<ProjectReference Include="..\EasyPay\Easypay.Rest.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Reporting\report-filters.js" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\InvoiceRepository.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>InvoiceRepository.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\InvoiceRepository.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>InvoiceRepository.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
