<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>aspnet-BancoAlimentar.AlimentaEstaIdeia.Web-8B472DE5-BD9B-4818-8B40-F8F81961E83A</UserSecretsId>
		<ApplicationInsightsResourceId>/subscriptions/f1b937fb-ca82-4eb6-a452-77af7a531344/resourceGroups/AlimenteEstaIdeia/providers/microsoft.insights/components/alimentaestaideia-core</ApplicationInsightsResourceId>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<DocumentationFile>obj\Debug\net10.0\BancoAlimentar.AlimentaEstaIdeia.Web.xml</DocumentationFile>
		<ImplicitUsings>disable</ImplicitUsings>
		<AnalysisLevel>latest</AnalysisLevel>
		<Nullable>annotations</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="stylecop.json" />
		<Content Remove="wwwroot\lib\datatables.net-plugins\datetime.js" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" />
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" />
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Azure.Storage.Queues" />
		<PackageReference Include="ClosedXML" />
		<PackageReference Include="DNTCaptcha.Core" />
		<PackageReference Include="HtmlRenderer.PdfSharp.NetStandard2" />
		<PackageReference Include="Humanizer" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.FeatureManagement.AspNetCore" />
		<PackageReference Include="Microsoft.Graph" />
		<PackageReference Include="Microsoft.Graph.Core" />
		<PackageReference Include="Microsoft.Kiota.Abstractions" />
		<PackageReference Include="NuGet.Packaging" />
		<PackageReference Include="NuGet.Protocol" />
		<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
		<PackageReference Include="MiniProfiler.AspNetCore.Mvc" />
		<PackageReference Include="MiniProfiler.EntityFrameworkCore" />
		<PackageReference Include="QRCoder" />
		<PackageReference Include="RestSharp" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Model\BancoAlimentar.AlimentaEstaIdeia.Model.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Repository\BancoAlimentar.AlimentaEstaIdeia.Repository.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.Core\BancoAlimentar.AlimentaEstaIdeia.Sas.Core.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.Model\BancoAlimentar.AlimentaEstaIdeia.Sas.Model.csproj" />
		<ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.Repository\BancoAlimentar.AlimentaEstaIdeia.Sas.Repository.csproj" />
		<ProjectReference Include="..\EasyPay\Easypay.Rest.Client.csproj" />
		<ProjectReference Include="..\Paypal\Paypal.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Admin\Pages\Invoices\" />
		<Folder Include="Areas\Admin\Pages\Users\" />
		<Folder Include="Areas\Identity\Data\" />
		<Folder Include="Data\Migrations\" />
		<Folder Include="wwwroot\lib\datatables.net-plugins\" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="PaypalManager\" />
		<None Remove="PayPalHttp" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\HeaderResources.es.resx" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="Pages\Tenants\bancoalimentar\Pages\_ViewImports.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot\img\comida.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Resources\Pages\Angola.resx">
	    <SubType>Designer</SubType>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Pages\CaboVerde.es.resx">
	    <SubType>Designer</SubType>
	  </EmbeddedResource>
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio><UserProperties wwwroot_4lib_4bootstrap_4css_4bootstrap-reboot_1min_1css_1map__JsonSchema="" /></VisualStudio>
	</ProjectExtensions>

</Project>
