/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Easypay.Rest.Client.Client.OpenAPIDateConverter;

namespace Easypay.Rest.Client.Model
{
    /// <summary>
    /// CheckoutPost201Response
    /// </summary>
    [DataContract(Name = "checkout_post_201_response")]
    public partial class CheckoutPost201Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutPost201Response" /> class.
        /// </summary>
        /// <param name="session">Session token to be used by the rest of the Checkout process..</param>
        /// <param name="config">Configuration properties..</param>
        /// <param name="id">id.</param>
        public CheckoutPost201Response(string session = default(string), Object config = default(Object), Guid id = default(Guid))
        {
            this.Session = session;
            this.Config = config;
            this.Id = id;
        }

        /// <summary>
        /// Session token to be used by the rest of the Checkout process.
        /// </summary>
        /// <value>Session token to be used by the rest of the Checkout process.</value>
        [DataMember(Name = "session", EmitDefaultValue = false)]
        public string Session { get; set; }

        /// <summary>
        /// Configuration properties.
        /// </summary>
        /// <value>Configuration properties.</value>
        [DataMember(Name = "config", EmitDefaultValue = false)]
        [Obsolete]
        public Object Config { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutPost201Response {\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
