/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Easypay.Rest.Client.Client.OpenAPIDateConverter;

namespace Easypay.Rest.Client.Model
{
    /// <summary>
    /// FrequentMethodSddMandate
    /// </summary>
    [DataContract(Name = "Frequent_method_sdd_mandate")]
    public partial class FrequentMethodSddMandate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FrequentMethodSddMandate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FrequentMethodSddMandate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FrequentMethodSddMandate" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="billingEntity">billingEntity.</param>
        /// <param name="iban">iban (required).</param>
        /// <param name="key">key.</param>
        /// <param name="countryCode">countryCode (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="phone">phone (required).</param>
        /// <param name="accountHolder">accountHolder (required).</param>
        /// <param name="maxNumDebits">maxNumDebits.</param>
        public FrequentMethodSddMandate(string id = default(string), string billingEntity = default(string), string iban = default(string), string key = default(string), string countryCode = default(string), string name = default(string), string email = default(string), string phone = default(string), string accountHolder = default(string), string maxNumDebits = default(string))
        {
            // to ensure "iban" is required (not null)
            if (iban == null)
            {
                throw new ArgumentNullException("iban is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.Iban = iban;
            // to ensure "countryCode" is required (not null)
            if (countryCode == null)
            {
                throw new ArgumentNullException("countryCode is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.CountryCode = countryCode;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.Name = name;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.Email = email;
            // to ensure "phone" is required (not null)
            if (phone == null)
            {
                throw new ArgumentNullException("phone is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.Phone = phone;
            // to ensure "accountHolder" is required (not null)
            if (accountHolder == null)
            {
                throw new ArgumentNullException("accountHolder is a required property for FrequentMethodSddMandate and cannot be null");
            }
            this.AccountHolder = accountHolder;
            this.Id = id;
            this.BillingEntity = billingEntity;
            this.Key = key;
            this.MaxNumDebits = maxNumDebits;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets BillingEntity
        /// </summary>
        [DataMember(Name = "billing_entity", EmitDefaultValue = false)]
        public string BillingEntity { get; set; }

        /// <summary>
        /// Gets or Sets Iban
        /// </summary>
        [DataMember(Name = "iban", IsRequired = true, EmitDefaultValue = true)]
        public string Iban { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [DataMember(Name = "country_code", IsRequired = true, EmitDefaultValue = true)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name = "phone", IsRequired = true, EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets AccountHolder
        /// </summary>
        [DataMember(Name = "account_holder", IsRequired = true, EmitDefaultValue = true)]
        public string AccountHolder { get; set; }

        /// <summary>
        /// Gets or Sets MaxNumDebits
        /// </summary>
        [DataMember(Name = "max_num_debits", EmitDefaultValue = false)]
        public string MaxNumDebits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FrequentMethodSddMandate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  BillingEntity: ").Append(BillingEntity).Append("\n");
            sb.Append("  Iban: ").Append(Iban).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  AccountHolder: ").Append(AccountHolder).Append("\n");
            sb.Append("  MaxNumDebits: ").Append(MaxNumDebits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
