/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Easypay.Rest.Client.Client.OpenAPIDateConverter;

namespace Easypay.Rest.Client.Model
{
    /// <summary>
    /// OutPaymentPost201Response
    /// </summary>
    [DataContract(Name = "_out_payment_post_201_response")]
    public partial class OutPaymentPost201Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutPaymentPost201Response" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="message">message.</param>
        /// <param name="id">id.</param>
        /// <param name="method">method.</param>
        /// <param name="customer">customer.</param>
        /// <param name="outAccount">outAccount.</param>
        public OutPaymentPost201Response(string status = default(string), Collection<string> message = default(Collection<string>), Guid id = default(Guid), OutPaymentPost201ResponseMethod method = default(OutPaymentPost201ResponseMethod), FrequentPost201ResponseCustomer customer = default(FrequentPost201ResponseCustomer), FrequentPost201ResponseCustomer outAccount = default(FrequentPost201ResponseCustomer))
        {
            this.Status = status;
            this.Message = message;
            this.Id = id;
            this.Method = method;
            this.Customer = customer;
            this.OutAccount = outAccount;
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /*
        <example>ok</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public Collection<string> Message { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public OutPaymentPost201ResponseMethod Method { get; set; }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>
        [DataMember(Name = "customer", EmitDefaultValue = false)]
        public FrequentPost201ResponseCustomer Customer { get; set; }

        /// <summary>
        /// Gets or Sets OutAccount
        /// </summary>
        [DataMember(Name = "out_account", EmitDefaultValue = false)]
        public FrequentPost201ResponseCustomer OutAccount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OutPaymentPost201Response {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  OutAccount: ").Append(OutAccount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
