/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Easypay.Rest.Client.Client.OpenAPIDateConverter;

namespace Easypay.Rest.Client.Model
{
    /// <summary>
    /// Indicates the current status of the refund. Possible values include: - waiting: The payment instruction has been given, but the chosen payment method requires confirmation from an external entity before the status of the operation is finalized. - pending: This is the initial state, and it means that the refund is queued. - success: The refund has been completed successfully. - failed: The refund could not be completed due to an error or issue.  This field provides a clear indication of the current state of the refund, helping users understand its progress and outcome.
    /// </summary>
    /// <value>Indicates the current status of the refund. Possible values include: - waiting: The payment instruction has been given, but the chosen payment method requires confirmation from an external entity before the status of the operation is finalized. - pending: This is the initial state, and it means that the refund is queued. - success: The refund has been completed successfully. - failed: The refund could not be completed due to an error or issue.  This field provides a clear indication of the current state of the refund, helping users understand its progress and outcome.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RefundStatus
    {
        /// <summary>
        /// Enum Success for value: success
        /// </summary>
        [EnumMember(Value = "success")]
        Success = 1,

        /// <summary>
        /// Enum Pending for value: pending
        /// </summary>
        [EnumMember(Value = "pending")]
        Pending = 2,

        /// <summary>
        /// Enum Failed for value: failed
        /// </summary>
        [EnumMember(Value = "failed")]
        Failed = 3,

        /// <summary>
        /// Enum Waiting for value: waiting
        /// </summary>
        [EnumMember(Value = "waiting")]
        Waiting = 4
    }

}
