/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Easypay.Rest.Client.Client.OpenAPIDateConverter;

namespace Easypay.Rest.Client.Model
{
    /// <summary>
    /// SubscriptionPostRequestCapture
    /// </summary>
    [DataContract(Name = "_subscription_post_request_capture")]
    public partial class SubscriptionPostRequestCapture : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionPostRequestCapture" /> class.
        /// </summary>
        /// <param name="transactionKey">The internal key used to identify this transaction in the merchant&#39;s database..</param>
        /// <param name="account">account.</param>
        /// <param name="descriptive">The description of the capture. Will be displayed in the bank statement or in the MB WAY application..</param>
        public SubscriptionPostRequestCapture(string transactionKey = default(string), CaptureIdPostRequestAccount account = default(CaptureIdPostRequestAccount), string descriptive = default(string))
        {
            this.TransactionKey = transactionKey;
            this.Account = account;
            this.Descriptive = descriptive;
        }

        /// <summary>
        /// The internal key used to identify this transaction in the merchant&#39;s database.
        /// </summary>
        /// <value>The internal key used to identify this transaction in the merchant&#39;s database.</value>
        [DataMember(Name = "transaction_key", EmitDefaultValue = false)]
        public string TransactionKey { get; set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name = "account", EmitDefaultValue = false)]
        public CaptureIdPostRequestAccount Account { get; set; }

        /// <summary>
        /// The description of the capture. Will be displayed in the bank statement or in the MB WAY application.
        /// </summary>
        /// <value>The description of the capture. Will be displayed in the bank statement or in the MB WAY application.</value>
        [DataMember(Name = "descriptive", EmitDefaultValue = false)]
        public string Descriptive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubscriptionPostRequestCapture {\n");
            sb.Append("  TransactionKey: ").Append(TransactionKey).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  Descriptive: ").Append(Descriptive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TransactionKey (string) maxLength
            if (this.TransactionKey != null && this.TransactionKey.Length > 50)
            {
                yield return new ValidationResult("Invalid value for TransactionKey, length must be less than 50.", new[] { "TransactionKey" });
            }

            // Descriptive (string) maxLength
            if (this.Descriptive != null && this.Descriptive.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Descriptive, length must be less than 255.", new[] { "Descriptive" });
            }

            yield break;
        }
    }

}
