// <auto-generated />
namespace Link.BA.Donate.WebSite.Migrations.GamificationDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nullablecolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullablecolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202102260116474_nullable columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
