<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
	  <AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
		<PackageReference Include="Microsoft.ApplicationInsights.DependencyCollector" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" />
		<PackageReference Include="MiniProfiler.Shared" />
		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Common\BancoAlimentar.AlimentaEstaIdeia.Common.csproj" />
	  <ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Model\BancoAlimentar.AlimentaEstaIdeia.Model.csproj" />
	  <ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider\BancoAlimentar.AlimentaEstaIdeia.Sas.ConfigurationProvider.csproj" />
	  <ProjectReference Include="..\BancoAlimentar.AlimentaEstaIdeia.Sas.Repository\BancoAlimentar.AlimentaEstaIdeia.Sas.Repository.csproj" />
	  <ProjectReference Include="..\EasyPay\Easypay.Rest.Client.csproj" />
	  <ProjectReference Include="..\Paypal\Paypal.csproj" />
	</ItemGroup>

</Project>
